### PR TITLE
feign.Request object now supported as exception constructor parameter

### PR DESCRIPTION
**Pull request by StefanFellinger**
The ExceptionGenerator now

* also looks for constructor parameter of type feign.Request.
* creates the exception providing the feign.Request by calling response.request()

### CODE REVIEW

**Comment by StefanFellinger** [comment]
Hey @saintf,

i've two questions: First, is this pull request fine for you? And second most important for me, when do you plan to release? 

Best regards,

Stefan

**Comment by StefanFellinger** [comment]
Hey @saintf ,

how are you? I would be happy if you tell me some time horizon i can calculate with getting a new version including my pull request :-)

Have a good time,

Stefan

**Comment by saintf** [comment]
Sorry Stefan!! Work and personal life have been brutal. I'll look at it
this weekend and if all good I'll release it then. Sorry it took me so
long!!!

**Comment by StefanFellinger** [comment]
Hey @saintf ,

oh i know, luckily i "only" have a bit of water in one of my cellar rooms, comming from somewhere outside. Now i have a new hobby: finding the source of water leaking. Most important family and friends are all healthy. So we actually work on a project replacing some legacy systems, so i have many items on my todos list.

**Comment by saintf** [comment]
Code looks good. thanks for paying attention to style and covering with tests (much much appreciated ;)). I've merged - and will release shortly.

**Pull request merged**
