### PR TITLE
Fix compatibility with 10.7.0

### PR DESCRIPTION
**Pull request by SimY4**

### CODE REVIEW

**Comment by SimY4** [comment]
ANy change this can be merged and released?

**Comment by SimY4** [comment]
@saintf can you please have a look? This change is currently blocking us from using any Feign version after 10.7.+

**Comment by saintf** [comment]
@SimY4 sorry for the delay. I've been unfortunately ill - but back now. Will take a look over the weekend.

**Review by saintf — APPROVED** [review]
Looks good - sorry it took so long

**Comment by SimY4** [comment]
@saintf no worries. I hope everything is alright now. 

Thank you for reviewing this change

**Pull request merged**
