### PR TITLE
Meta annotations support

### LINKED ISSUE #31: Meta-annotation support
Mainly in combination with spring-cloud-openfeign it would be really helpfull to have support for meta-annotations.
This will reduce the amount of annotations in the interface.

The idea is to have a custom annotation which combines the `@RequestMapping` annotations with the `@ErrorHandling` annotation on a method/class level. the SpringDecoder is able to work with the meta-annotations already so it is more consistent to have also `@ErrorHandling` working in a meta-annotation

e.g.

```java
@ErrorHandling(codeSpecific =
    {
        @ErrorCodes( codes = {401}, generate = UnAuthorizedException.class),
        @ErrorCodes( codes = {403}, generate = ForbiddenException.class),
        @ErrorCodes( codes = {404}, generate = UnknownItemException.class),
    },
    defaultException = MethodLevelDefaultException.class
)
@RequestMapping(method = RequestMethod.GET, consumes = APPLICATION_CBOR_VALUE, produces = APPLICATION_CBOR_VALUE)
@Target(ElementType.METHOD)
@Retention(RetentionPolicy.RUNTIME)
public @interface GetMappingWithErrorHandling {
    @AliasFor(annotation = RequestMapping.class)
    String[] path() default {};
}
```

and so it is possible to have in the interface only one annotation

```java
public interface GitHub {
    @GetMappingWithErrorHandling(path="https://github.com/projects"
    List<Contributor> projects();
}
```

### PR DESCRIPTION
**Pull request by BigMichi1**
this is a pull request against 1.0.3 to support meta-annotations when trying to find the `@ErrorHandling` annotation on a class/interface or method

it would be really nice if this can be merged against 1.0.3 and a new 1.0.4 will be released because we can not upgrade to OpenFeign 10.x right now

this will fix #31

### CODE REVIEW

**Review by saintf — CHANGES_REQUESTED** [review]
Can you add a "how-to" or so on the readme - explaining what the usecase is and how to use it (I get how it works and reduces what would otherwise likely be boiler-plate code)?

Also - is the expectation that you use the meta annotations OR the explicit ones (but not both at the same time?) Not sure how they're meant to interact, but if they don't play well, we either need to make them play well with eachother (with test cases) or make sure that we are explicit in our How-to as well as add cases that force us not to mix-and-match (I picture when someone wants a generic version of handling a given set of standard errors - but a specific code on a specific class should generate something else and hence they add the meta-annotation plus one code on error handling...  - what would then be the expected behaviour?

**Comment by BigMichi1** [comment]
will improve it

**Comment by BigMichi1** [comment]
@saintf i added some more test cases and also added the meta-annotations support to the README, would be nice if you can check again and let me know about further improvements

**Comment by BigMichi1** [comment]
the PR is now also against master as it is easier to add this functionality

**Comment by BigMichi1** [comment]
@saintf anything left here that i need to improve?

**Comment by BigMichi1** [comment]
has been merged into the official repo https://github.com/OpenFeign/feign/issues/1457

**Pull request closed without merging**
